version: "3.8"
services:
  postgres:
    image: postgres:13.2 #TODO update as needed
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:6.4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost.com 
      PGADMIN_DEFAULT_PASSWORD: Postgres123 
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET:  my-admin-secret 
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
volumes:
  db_data: